# Generated by Django 5.2 on 2025-08-04 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(choices=[("tumblr", "Tumblr")], max_length=240),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.TextField(blank=True, db_index=True, null=True, unique=True),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.study"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state"], name="core_servic_state_8fa4d5_idx")
                ],
            },
        ),
    ]
