# Generated by Django 5.2 on 2025-08-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serviceaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
