# Generated by Django 5.2 on 2025-08-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_serviceaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceaccount",
            name="access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="serviceaccount",
            name="expires_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="serviceaccount",
            name="state",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
