# Generated by Django 5.2 on 2025-08-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_serviceaccount_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceaccount",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
