# Generated by Django 5.2 on 2025-08-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_study_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("tumblr", "Tumblr"), ("strava", "Strava")],
                        max_length=240,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vertical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[("feed post", "Feed Post")], max_length=24
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="serviceaccount",
            name="core_servic_state_8fa4d5_idx",
        ),
        migrations.RemoveField(
            model_name="serviceaccount",
            name="name",
        ),
        migrations.AddField(
            model_name="serviceaccount",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.service",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="services",
            field=models.ManyToManyField(to="core.service"),
        ),
        migrations.AddField(
            model_name="service",
            name="verticals",
            field=models.ManyToManyField(to="core.vertical"),
        ),
    ]
