# Generated by Django 5.2 on 2025-08-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_service_vertical_and_more"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaccount",
            name="completed_donation_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceaccount",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sessions.session",
            ),
        ),
    ]
