# Generated by Django 5.2 on 2026-03-05 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_initial_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_type', models.CharField(choices=[('tumblr_dashboard_post', 'Tumblr Dashboard Post')], max_length=240)),
                ('service_post_id', models.CharField(max_length=240)),
                ('raw_data', models.JSONField()),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_posts', to='core.serviceaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
